export const gamesDB = [
  {
    "id": 1294,
    "title": "Die Young (IndieGala) Giveaway",
    "worth": 19.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61aa6ac241369.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61aa6ac241369.jpg",
    "description": "Get Die Young for free via IndieGala! Die Young is a first-person open-world survival game with astonishing landscapes and lots of suspense. Grab it now!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/die-young",
    "published_date": "2023-03-08 12:11:49",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 13610,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/die-young",
    "open_giveaway": "https://www.gamerpower.com/open/die-young"
  },
  {
    "id": 1557,
    "title": "Felix The Toy (itchio) Giveaway",
    "worth": 1.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/62b274ef6b0d7.jpg",
    "image": "https://www.gamerpower.com/offers/1b/62b274ef6b0d7.jpg",
    "description": "Grab Felix The Toy for free via itch.io! Felix The Toy is an indie game inspired by the PlayStation game, Toy Story 2.",
    "instructions": "1. Click the button \"Download or Claim\" before the offer expires.\r\n2. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/felix-the-toy-itchio",
    "published_date": "2023-03-07 19:51:09",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "2023-03-31 23:59:29",
    "users": 4850,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/felix-the-toy-itchio",
    "open_giveaway": "https://www.gamerpower.com/open/felix-the-toy-itchio"
  },
  {
    "id": 2276,
    "title": "Figment (GOG) Giveaway",
    "worth": 19.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/64062da817567.jpg",
    "image": "https://www.gamerpower.com/offers/1b/64062da817567.jpg",
    "description": "Score Figment for free via GOG! Plus it's DRM-Free! Figment is an action-adventure game with a unique surreal universe filled with music and humor.",
    "instructions": "1. Click the \"Go to giveaway\" green button and you will be redirected to the GOG home page\r\n2. Scroll down until you find the game banner.\r\n3. Click the \"Get it Free\" button and login into your GOG account to unlock the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/figment-gog-giveaway",
    "published_date": "2023-03-06 13:15:04",
    "type": "Game",
    "platforms": "PC, GOG",
    "end_date": "2023-03-09 23:59:00",
    "users": 1880,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/figment-gog-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/figment-gog-giveaway"
  },
  {
    "id": 722,
    "title": "Black Desert (Steam) Giveaway",
    "worth": 9.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6038682e45a15.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6038682e45a15.jpg",
    "description": "Grab Black Desert Online for free on Steam! Black Desert Online is a popular open-world action MMORPG with impressive graphics. ",
    "instructions": "1. Download directly via Steam before 9 Mar. That's it!\r\n2. Enjoy your new Steam game!",
    "open_giveaway_url": "https://www.gamerpower.com/open/free-black-desert-online-steam",
    "published_date": "2023-03-02 13:22:27",
    "type": "Game",
    "platforms": "PC, Steam",
    "end_date": "N/A",
    "users": 24580,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/free-black-desert-online-steam",
    "open_giveaway": "https://www.gamerpower.com/open/free-black-desert-online-steam"
  },
  {
    "id": 2273,
    "title": "Figment (Steam) Giveaway",
    "worth": 19.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6400e74e47496.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6400e74e47496.jpg",
    "description": "Score Figment for free via Steam! Grab it before March 9th and it's yours forever! Figment is an action-adventure game with a unique surreal universe. Grab it now!",
    "instructions": "1. Download directly via Steam before the offer expires.\r\n2. That's it! Enjoy your new Steam game!",
    "open_giveaway_url": "https://www.gamerpower.com/open/figment-steam-giveaway",
    "published_date": "2023-03-02 13:13:34",
    "type": "Game",
    "platforms": "PC, Steam",
    "end_date": "2023-03-09 23:59:00",
    "users": 5530,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/figment-steam-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/figment-steam-giveaway"
  },
  {
    "id": 2272,
    "title": "Colorful Recolor (GX.games) Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6400d66e34ee6.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6400d66e34ee6.jpg",
    "description": "Claim Colorful Recolor for free via GX.games and Opera Gx! Colorful Recolor is a fast-paced puzzle game with 100 unique puzzles. Check it out!",
    "instructions": "1. To claim the game you have to install Opera Gx (a free browser for gamers).\r\n2. Go to GX.games via the GX corner button or the browser.\r\n3 Sign in with your Opera account or create an account.\r\n4. Click the button to claim the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/colorful-recolor-gx-games-giveaway",
    "published_date": "2023-03-02 12:01:34",
    "type": "Game",
    "platforms": "PC",
    "end_date": "2023-03-16 23:59:00",
    "users": 2150,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/colorful-recolor-gx-games-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/colorful-recolor-gx-games-giveaway"
  },
  {
    "id": 2271,
    "title": "Rise of Industry (Epic Games) Giveaway",
    "worth": 29.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6400d2397d747.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6400d2397d747.jpg",
    "description": "Epic Games Store is giving away Rise of Industry for free! Rise of Industry is a fun strategic tycoon game where you build your growing industrial empire. Put your entrepreneurial skills to the test!",
    "instructions": "1. Login into your Epic Games Store account.\r\n2. Click the button to add the game to your library",
    "open_giveaway_url": "https://www.gamerpower.com/open/rise-of-industry-epic-games-giveaway",
    "published_date": "2023-03-02 11:43:37",
    "type": "Game",
    "platforms": "PC, Epic Games Store",
    "end_date": "2023-03-09 23:59:00",
    "users": 3530,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/rise-of-industry-epic-games-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/rise-of-industry-epic-games-giveaway"
  },
  {
    "id": 1405,
    "title": "Lords Mobile 7th Anniversary Key Giveaway",
    "worth": 350.0,
    "thumbnail": "https://www.gamerpower.com/offers/1/62106a5400751.jpg",
    "image": "https://www.gamerpower.com/offers/1b/62106a5400751.jpg",
    "description": "Claim your Lords Mobile Special Gift Pack Key (350 value) and unlock lots of in-game items for Lords Mobile (including PC version and Mobile)!. Please note this giveaway is for new players only and you must redeem your key within 24 hours of registration.",
    "instructions": "1. Log in to your free MMOBomb account.\r\n2. Click the button to unlock your key and follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/lords-mobile-special-gift-pack-key-giveaway",
    "published_date": "2023-03-01 15:59:37",
    "type": "DLC",
    "platforms": "PC, Android, iOS",
    "end_date": "2023-03-31 23:59:00",
    "users": 5600,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/lords-mobile-special-gift-pack-key-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/lords-mobile-special-gift-pack-key-giveaway"
  },
  {
    "id": 1419,
    "title": "Last Dream (IndieGala) Giveaway",
    "worth": 9.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/622b7772e9ad9.jpg",
    "image": "https://www.gamerpower.com/offers/1b/622b7772e9ad9.jpg",
    "description": "Download Last Dream for free via IndieGala! Last Dream is an indie old-school single-player RPG. Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/last-dream",
    "published_date": "2023-02-24 17:00:08",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 7770,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/last-dream",
    "open_giveaway": "https://www.gamerpower.com/open/last-dream"
  },
  {
    "id": 2264,
    "title": "Chef Life - BON APPÉTIT PACK (Steam)",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/63f793e68d48d.jpg",
    "image": "https://www.gamerpower.com/offers/1b/63f793e68d48d.jpg",
    "description": "Claim your Chef Life - BON APPÉTIT PACK (DLC) on Steam for free! Please note the base game Chef Life: A Restaurant Simulator is required to enjoy this DLC content.",
    "instructions": "1. Download this DLC content directly via Steam before expires (9 Mar).\r\n2. Don't forget the base game is required.",
    "open_giveaway_url": "https://www.gamerpower.com/open/chef-life-bon-appetit-pack-steam",
    "published_date": "2023-02-23 11:27:18",
    "type": "DLC",
    "platforms": "PC, Steam",
    "end_date": "2023-03-09 23:59:00",
    "users": 3060,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/chef-life-bon-appetit-pack-steam",
    "open_giveaway": "https://www.gamerpower.com/open/chef-life-bon-appetit-pack-steam"
  },
  {
    "id": 1507,
    "title": "Drop Hunt (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/62886f6fbfe5c.jpg",
    "image": "https://www.gamerpower.com/offers/1b/62886f6fbfe5c.jpg",
    "description": "Score Drop Hunt - Adventure Puzzle for free on IndieGala and solve eighty puzzle levels that are spread across four locations!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/drop-hunt-adventure-puzzle",
    "published_date": "2023-02-21 10:43:43",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 5840,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/drop-hunt-adventure-puzzle",
    "open_giveaway": "https://www.gamerpower.com/open/drop-hunt-adventure-puzzle"
  },
  {
    "id": 905,
    "title": "Free Larger Than Light (itch.io) Giveaway",
    "worth": 5.0,
    "thumbnail": "https://www.gamerpower.com/offers/1/60b608dd99d89.jpg",
    "image": "https://www.gamerpower.com/offers/1b/60b608dd99d89.jpg",
    "description": "Grab Larger Than Light for free on itch.io!  Larger Than Light is a 2.5D puzzle platform game with fully voiced dialogue. Download now!",
    "instructions": "1. Click the button \"Download or Claim\" before the offer expires.\r\n2. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/free-larger-than-light",
    "published_date": "2023-02-18 18:34:12",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "N/A",
    "users": 16580,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/free-larger-than-light",
    "open_giveaway": "https://www.gamerpower.com/open/free-larger-than-light"
  },
  {
    "id": 1462,
    "title": "King of Dragon Pass (IndieGala) Giveaway",
    "worth": 11.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/625a3d01bddbb.jpg",
    "image": "https://www.gamerpower.com/offers/1b/625a3d01bddbb.jpg",
    "description": "Claim King of Dragon Pass for free via IndieGala and create your own epic saga of survival! King of Dragon Pass is a unique mix of RPG, strategy, and story-telling! Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/king-of-dragon-pass",
    "published_date": "2023-02-17 21:26:39",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 10120,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/king-of-dragon-pass",
    "open_giveaway": "https://www.gamerpower.com/open/king-of-dragon-pass"
  },
  {
    "id": 2246,
    "title": "Adorables (IndieGala) Giveaway",
    "worth": 2.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/63ebe809d49dd.jpg",
    "image": "https://www.gamerpower.com/offers/1b/63ebe809d49dd.jpg",
    "description": "Grab Adorables without any cost on IndieGala! Adorables is a indie multiplayer game with 6 game modes including Soccer, Beach ball, CTF, Last Adorable Standing, Ice Hockey and Mummy.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/adorables-indiegala-giveaway",
    "published_date": "2023-02-14 14:59:05",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 3170,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/adorables-indiegala-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/adorables-indiegala-giveaway"
  },
  {
    "id": 1474,
    "title": "Lamp Head (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6262ed316973d.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6262ed316973d.jpg",
    "description": "Claim a free copy of Lamp Head via IndieGala! Lamp Head is a small indie game where you play as a strange man with a lamp in his head.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/lamp-head",
    "published_date": "2023-02-10 13:13:41",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 7360,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/lamp-head",
    "open_giveaway": "https://www.gamerpower.com/open/lamp-head"
  },
  {
    "id": 1455,
    "title": "Control Craft 2 (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/62544fcbac24e.jpg",
    "image": "https://www.gamerpower.com/offers/1b/62544fcbac24e.jpg",
    "description": "Score Control Craft 2 for free on IndieGala! Control Craft 2 is a casual real-time strategy game. Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/control-craft-2",
    "published_date": "2023-02-06 17:14:52",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 6210,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/control-craft-2",
    "open_giveaway": "https://www.gamerpower.com/open/control-craft-2"
  },
  {
    "id": 1451,
    "title": "Grab the Bottle (IndieGala) Giveaway",
    "worth": 2.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/625056717ce7e.jpg",
    "image": "https://www.gamerpower.com/offers/1b/625056717ce7e.jpg",
    "description": "Score a free copy of Grab the Bottle on IndieGala! Grab the Bottle is a colorful puzzle game in which you solve puzzles by stretching and retracting your arm. Download it now!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/grab-the-bottle",
    "published_date": "2023-02-03 16:09:19",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 5710,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/grab-the-bottle",
    "open_giveaway": "https://www.gamerpower.com/open/grab-the-bottle"
  },
  {
    "id": 1411,
    "title": "Hamsterdam (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/621ba47e13b7a.jpg",
    "image": "https://www.gamerpower.com/offers/1b/621ba47e13b7a.jpg",
    "description": "Download Hamsterdam for free via IndieGala and become the Hamster-fu master! Hamsterdam is a classic brawler with rhythm combos and frantic action.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/hamsterdam",
    "published_date": "2023-01-30 18:00:13",
    "type": "Game",
    "platforms": "PC",
    "end_date": "N/A",
    "users": 14030,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/hamsterdam",
    "open_giveaway": "https://www.gamerpower.com/open/hamsterdam"
  },
  {
    "id": 1390,
    "title": "Revolution Ace (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61f446a2ea194.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61f446a2ea194.jpg",
    "description": "Get Revolution Ace for free on IndieGala! Revolution Ace is a fun shoot'em up with online and local two player co-op. Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/revolution-ace",
    "published_date": "2023-01-20 18:16:16",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 9220,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/revolution-ace",
    "open_giveaway": "https://www.gamerpower.com/open/revolution-ace"
  },
  {
    "id": 2204,
    "title": "Dual Chroma: Academy Carols (itch.io) Giveaway",
    "worth": 2.0,
    "thumbnail": "https://www.gamerpower.com/offers/1/63c6f67bb9c8b.jpg",
    "image": "https://www.gamerpower.com/offers/1b/63c6f67bb9c8b.jpg",
    "description": "Grab Dual Chroma: Academy Carols for free on itch.io! Dual Chroma: Academy Carols is a slice-of-life Visual Novel. Check it out, If you are a fan of this type of game!",
    "instructions": "1. Click the button \"Download or Claim\" before the offer expires.\r\n2. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/dual-chroma-academy-carols-itch-io-giveaway",
    "published_date": "2023-01-17 20:26:51",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "N/A",
    "users": 4840,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/dual-chroma-academy-carols-itch-io-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/dual-chroma-academy-carols-itch-io-giveaway"
  },
  {
    "id": 1380,
    "title": "Last Horizon (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61eafec633d93.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61eafec633d93.jpg",
    "description": "Download Last Horizon for free via IndieGala! Last Horizon is an atmospheric space exploration game. Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/last-horizon",
    "published_date": "2023-01-16 18:13:19",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 9610,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/last-horizon",
    "open_giveaway": "https://www.gamerpower.com/open/last-horizon"
  },
  {
    "id": 1376,
    "title": "Alone on Mars (IndieGala) Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61e306d23101e.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61e306d23101e.jpg",
    "description": "Download Alone on Mars for free on IndieGala! Alone on Mars is an indie 2D survival shooter game on Mars.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/alone-on-mars",
    "published_date": "2023-01-13 20:25:43",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 7950,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/alone-on-mars",
    "open_giveaway": "https://www.gamerpower.com/open/alone-on-mars"
  },
  {
    "id": 1368,
    "title": "Six Sides of the World (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61df28b79cabf.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61df28b79cabf.jpg",
    "description": "Download Six Sides of the World for free on IndieGala! Six Sides of the World is a fun puzzle game with lots of cubes and portals!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/six-sides-of-the-world",
    "published_date": "2023-01-09 19:23:41",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 9000,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/six-sides-of-the-world",
    "open_giveaway": "https://www.gamerpower.com/open/six-sides-of-the-world"
  },
  {
    "id": 1239,
    "title": "Glorkian Warrior: The Trials Of Glork Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61927b38a2bb5.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61927b38a2bb5.jpg",
    "description": "Download Glorkian Warrior: The Trials Of Glork for free on IndieGala! Glorkian Warrior: The Trials Of Glork is a fun comic-styled shoot-em-up with simple platforming action. Get it now!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/glorkian-warrior-the-trials-of-glork",
    "published_date": "2023-01-02 19:33:20",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 8200,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/glorkian-warrior-the-trials-of-glork",
    "open_giveaway": "https://www.gamerpower.com/open/glorkian-warrior-the-trials-of-glork"
  },
  {
    "id": 1356,
    "title": "Nostradamus: The Last Prophecy Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61d37533c7edf.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61d37533c7edf.jpg",
    "description": "Grab Nostradamus: The Last Prophecy for free on IndieGala! Are you ready to join this supernatural adventure?",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/nostradamus-the-last-prophecy",
    "published_date": "2023-01-01 04:48:48",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 10120,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/nostradamus-the-last-prophecy",
    "open_giveaway": "https://www.gamerpower.com/open/nostradamus-the-last-prophecy"
  },
  {
    "id": 2115,
    "title": "Holiday Bonus GOLD (IndieGala) Giveaway",
    "worth": 6.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/63a9e9ffd9b3b.jpg",
    "image": "https://www.gamerpower.com/offers/1b/63a9e9ffd9b3b.jpg",
    "description": "Download Holiday Bonus GOLD for free on IndieGala! Holiday Bonus GOLD is a match-3 game with a winter theme.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/holiday-bonus-gold-indiegala-giveaway",
    "published_date": "2022-12-26 19:37:51",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 5540,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/holiday-bonus-gold-indiegala-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/holiday-bonus-gold-indiegala-giveaway"
  },
  {
    "id": 1272,
    "title": "Potatoman Seeks the Troof (IndieGala) Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/619e81c026570.jpg",
    "image": "https://www.gamerpower.com/offers/1b/619e81c026570.jpg",
    "description": "Download Potatoman Seeks the Troof for free on IndieGala! Potatoman Seeks the Troof is a challenging platforming adventure from Pixeljam Games. Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/potatoman-seeks-the-troof",
    "published_date": "2022-12-22 02:26:23",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 7870,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/potatoman-seeks-the-troof",
    "open_giveaway": "https://www.gamerpower.com/open/potatoman-seeks-the-troof"
  },
  {
    "id": 1308,
    "title": "Snowball (IndieGala) Giveaway",
    "worth": 2.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/61b77c476490a.jpg",
    "image": "https://www.gamerpower.com/offers/1b/61b77c476490a.jpg",
    "description": "Grab Snowball for free on IndieGala! Snowball is a winter pinball adventure with a  more \"discovery-based\" approach to pinball. Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/snowball",
    "published_date": "2022-12-19 17:31:44",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 10290,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/snowball",
    "open_giveaway": "https://www.gamerpower.com/open/snowball"
  },
  {
    "id": 2087,
    "title": "NORTH (IndieGala) Giveaway",
    "worth": 1.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/639cb3bdb51e8.jpg",
    "image": "https://www.gamerpower.com/offers/1b/639cb3bdb51e8.jpg",
    "description": "IndieGala is giving away NORTH without any cost! NORTH is a small sci-fi indie game filled with strange creatures.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/north-indiegala-giveaway",
    "published_date": "2022-12-16 19:06:53",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 6180,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/north-indiegala-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/north-indiegala-giveaway"
  },
  {
    "id": 2080,
    "title": "Suna (IndieGala) Giveaway",
    "worth": 2.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6397554ed1c7d.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6397554ed1c7d.jpg",
    "description": "Grab a free copy of Suna via IndieGala! Suna is a small indie adventure game about a lost man.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/suna-indiegala-giveaway",
    "published_date": "2022-12-12 17:22:38",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 6150,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/suna-indiegala-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/suna-indiegala-giveaway"
  },
  {
    "id": 2064,
    "title": "Gravity Den",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/638e2aac26aea.jpg",
    "image": "https://www.gamerpower.com/offers/1b/638e2aac26aea.jpg",
    "description": "Score Gravity Den for free on IndieGala! Gravity Den is a 2d platformer with a one-eyed alien. Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/gravity-den",
    "published_date": "2022-12-05 18:30:20",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 5900,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/gravity-den",
    "open_giveaway": "https://www.gamerpower.com/open/gravity-den"
  },
  {
    "id": 1190,
    "title": "Secrets of Magic: The Book of Spells (IndieGala) Giveaway",
    "worth": 9.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6174181172715.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6174181172715.jpg",
    "description": "Score Secrets of Magic: The Book of Spells for free on IndieGala and dive into a magical world of witches and wizards! Check it out!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/secrets-of-magic-the-book-of-spells",
    "published_date": "2022-12-01 04:34:09",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 9720,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/secrets-of-magic-the-book-of-spells",
    "open_giveaway": "https://www.gamerpower.com/open/secrets-of-magic-the-book-of-spells"
  },
  {
    "id": 2055,
    "title": "Mumps (IndieGala) Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6384f38954faa.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6384f38954faa.jpg",
    "description": "Grab Mumps for free on IndieGala! Mumps is a small 2D indie platformer with a pink pig.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/mumps",
    "published_date": "2022-11-28 18:44:41",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 6040,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/mumps",
    "open_giveaway": "https://www.gamerpower.com/open/mumps"
  },
  {
    "id": 2047,
    "title": "Yashik (IndieGala) Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/637c29e420e56.jpg",
    "image": "https://www.gamerpower.com/offers/1b/637c29e420e56.jpg",
    "description": "Grab Yashik for free on IndieGala! Yashik is an indie puzzle game with 2d graphics.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/yashik",
    "published_date": "2022-11-22 02:46:12",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 6920,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/yashik",
    "open_giveaway": "https://www.gamerpower.com/open/yashik"
  },
  {
    "id": 1123,
    "title": "Leisure Suit Larry - Magna Cum Laude Uncut and Uncensored (IndieGala) Giveaway",
    "worth": 5.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6145e6ed21b4e.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6145e6ed21b4e.jpg",
    "description": "Grab Leisure Suit Larry - Magna Cum Laude Uncut and Uncensored for free via IndieGala! And follow Larry's hilarious exploits and misadventures now in 3D!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/leisure-suit-larry-magna-cum-laude-uncut-and-uncensored",
    "published_date": "2022-11-16 20:21:31",
    "type": "Game",
    "platforms": "PC",
    "end_date": "N/A",
    "users": 15950,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/leisure-suit-larry-magna-cum-laude-uncut-and-uncensored",
    "open_giveaway": "https://www.gamerpower.com/open/leisure-suit-larry-magna-cum-laude-uncut-and-uncensored"
  },
  {
    "id": 2031,
    "title": "Extreme Racing on Highway (IndieGala) Giveaway",
    "worth": 10.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/636fc0d29af46.jpg",
    "image": "https://www.gamerpower.com/offers/1b/636fc0d29af46.jpg",
    "description": "Download Extreme Racing on Highway for free on IndieGala! Extreme Racing on Highway is an indie endless racing game.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/extreme-racing-on-highway",
    "published_date": "2022-11-12 16:50:42",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 11130,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/extreme-racing-on-highway",
    "open_giveaway": "https://www.gamerpower.com/open/extreme-racing-on-highway"
  },
  {
    "id": 490,
    "title": "Free Dead Hungry Diner (IndieGala) Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/5f9ad8bd10122.jpg",
    "image": "https://www.gamerpower.com/offers/1b/5f9ad8bd10122.jpg",
    "description": "Score Dead Hungry Diner on PC for free via IndieGala! Dead Hungry Diner is a single-player 2D Puzzle game with combos, spells and lots of monsters.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/free-dead-hungry-diner-pc",
    "published_date": "2022-11-01 07:33:51",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 14690,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/free-dead-hungry-diner-pc",
    "open_giveaway": "https://www.gamerpower.com/open/free-dead-hungry-diner-pc"
  },
  {
    "id": 2008,
    "title": "Secrets of Magic 2: Witches and Wizards",
    "worth": 9.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/635d71314ae0b.jpg",
    "image": "https://www.gamerpower.com/offers/1b/635d71314ae0b.jpg",
    "description": "Score Secrets of Magic 2: Witches and Wizards for free on IndieGala! Secrets of Magic 2: Witches and Wizards is a casual match-3 puzzle game with power-ups.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/secrets-of-magic-2-witches-and-wizards",
    "published_date": "2022-10-29 20:30:09",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 7720,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/secrets-of-magic-2-witches-and-wizards",
    "open_giveaway": "https://www.gamerpower.com/open/secrets-of-magic-2-witches-and-wizards"
  },
  {
    "id": 2007,
    "title": "Ghost of Tomorrow: Chapter 1",
    "worth": 3.0,
    "thumbnail": "https://www.gamerpower.com/offers/1/635c465548fde.jpg",
    "image": "https://www.gamerpower.com/offers/1b/635c465548fde.jpg",
    "description": "Grab Ghost of Tomorrow: Chapter 1 for free on itch.io! Ghost of Tomorrow is a psychological-horror first-person game. Check it out!",
    "instructions": "1. Click the button \"Download or Claim\" before the offer expires.\r\n2. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/ghost-of-tomorrow-chapter-1",
    "published_date": "2022-10-28 23:15:01",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "N/A",
    "users": 7000,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/ghost-of-tomorrow-chapter-1",
    "open_giveaway": "https://www.gamerpower.com/open/ghost-of-tomorrow-chapter-1"
  },
  {
    "id": 512,
    "title": "Free Contract With The Devil (PC)",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/5faa86cfce12c.jpg",
    "image": "https://www.gamerpower.com/offers/1b/5faa86cfce12c.jpg",
    "description": "Get Contract With The Devil on PC for free via IndieGala! Contract With The Devil is a Hidden Object game with great graphics and interesting puzzles!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/free-contract-with-the-devil-pc",
    "published_date": "2022-10-26 01:20:04",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 13530,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/free-contract-with-the-devil-pc",
    "open_giveaway": "https://www.gamerpower.com/open/free-contract-with-the-devil-pc"
  },
  {
    "id": 1971,
    "title": "Qvabllock (IndieGala) Giveaway",
    "worth": 3.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/634d74d19e74b.jpg",
    "image": "https://www.gamerpower.com/offers/1b/634d74d19e74b.jpg",
    "description": "Claim Qvabllock for free on IndieGala! Qvabllock is a minimalistic puzzle game with old-school pixel graphics.",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/qvabllock",
    "published_date": "2022-10-17 17:29:21",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 6540,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/qvabllock",
    "open_giveaway": "https://www.gamerpower.com/open/qvabllock"
  },
  {
    "id": 1962,
    "title": "RUN! GRANDPA! RUN! (IndieGala) Giveaway",
    "worth": 4.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/6341d5e6672a2.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6341d5e6672a2.jpg",
    "description": "Download a free copy of RUN! GRANDPA! RUN! on IndieGala! RUN! GRANDPA! RUN! is a platformer where you help Grandpa run!",
    "instructions": "1. Login into your free IndieGala account.\r\n2. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n3. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/run-grandpa-run",
    "published_date": "2022-10-08 21:56:22",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 7430,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/run-grandpa-run",
    "open_giveaway": "https://www.gamerpower.com/open/run-grandpa-run"
  },
  {
    "id": 1604,
    "title": "Dora Diginoid: Metroidvania sci-fi adventure game",
    "worth": 6.0,
    "thumbnail": "https://www.gamerpower.com/offers/1/62dec9fa9312b.jpg",
    "image": "https://www.gamerpower.com/offers/1b/62dec9fa9312b.jpg",
    "description": "Grab Dora Diginoid for free on itch.io! Dora Diginoid is an indie Metroidvania sci-fi adventure game where you explore the base 17.",
    "instructions": "1. Click the button \"Download or Claim\" before the offer expires.\r\n2. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/dora-diginoid-metroidvania-sci-fi-adventure-game",
    "published_date": "2022-07-25 18:51:06",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "N/A",
    "users": 9090,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/dora-diginoid-metroidvania-sci-fi-adventure-game",
    "open_giveaway": "https://www.gamerpower.com/open/dora-diginoid-metroidvania-sci-fi-adventure-game"
  },
  {
    "id": 1408,
    "title": "Slapshot Rebound In-Game Currency Key (5 Value)",
    "worth": 5.0,
    "thumbnail": "https://www.gamerpower.com/offers/1/62155af149804.jpg",
    "image": "https://www.gamerpower.com/offers/1b/62155af149804.jpg",
    "description": "Grab your free Slapshot Rebound 5 in-game currency key and take to the ice in style!",
    "instructions": "1. Login in to your Alienware Arena account and click the button to unlock your key.\r\n2. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/slapshot-rebound-in-game-currency-key-5-value",
    "published_date": "2022-02-22 22:51:45",
    "type": "DLC",
    "platforms": "PC",
    "end_date": "N/A",
    "users": 6080,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/slapshot-rebound-in-game-currency-key-5-value",
    "open_giveaway": "https://www.gamerpower.com/open/slapshot-rebound-in-game-currency-key-5-value"
  },
  {
    "id": 842,
    "title": "Metal Slug 3 Giveaway",
    "worth": 7.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/60840890f04f4.jpg",
    "image": "https://www.gamerpower.com/offers/1b/60840890f04f4.jpg",
    "description": "Grab Metal Slug 3 for free via Microsoft Store (Gold not required)!",
    "instructions": "1. Download via Microsoft Store before the offer expires!\r\n2. That's it, have fun!",
    "open_giveaway_url": "https://www.gamerpower.com/open/metal-slug-3",
    "published_date": "2021-04-24 14:01:21",
    "type": "Game",
    "platforms": "Xbox Series X|S, Xbox One",
    "end_date": "N/A",
    "users": 36530,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/metal-slug-3",
    "open_giveaway": "https://www.gamerpower.com/open/metal-slug-3"
  },
  {
    "id": 4,
    "title": "Get The Witcher: Enhanced Edition for FREE!",
    "worth": 9.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/5ec4fdb8dbe80.jpg",
    "image": "https://www.gamerpower.com/offers/1b/5ec4fdb8dbe80.jpg",
    "description": "Starting today, all GOG users can grab a free copy of The Witcher: Enhanced Edition Director's Cut! You just need to follow the instructions below!",
    "instructions": "1. Add <a href=\"https://www.gog.com/game/gwent_the_witcher_card_game\">Gwent</a> to your library on GOG\r\n2. Visit the <a href=\"https://www.gog.com/gwent-welcome-bonus\">giveaway page</a> and subscribe.\r\n3. Then go to <a href=\"https://www.gog.com/game/the_witcher\">The Witcher page</a> to unlock the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/get-the-witcher-enhanced-edition-for-free",
    "published_date": "2020-12-04 16:51:52",
    "type": "Game",
    "platforms": "PC, GOG",
    "end_date": "N/A",
    "users": 427520,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/get-the-witcher-enhanced-edition-for-free",
    "open_giveaway": "https://www.gamerpower.com/open/get-the-witcher-enhanced-edition-for-free"
  },
  {
    "id": 441,
    "title": "Free NiGHTS Into Dreams (Steam) Giveaway",
    "worth": 7.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/5f873986428d4.jpg",
    "image": "https://www.gamerpower.com/offers/1b/5f873986428d4.jpg",
    "description": "Grab NiGHTS Into Dreams for free! That's right, Sega is celebrating their 60th anniversary and they are giving away NiGHTS Into Dreams entirely for free! To grab your copy you just need to sign up with your email and Steam account. It's that easy!",
    "instructions": "1. Sign in with your email and click continue.\r\n2. Login with your Steam account.",
    "open_giveaway_url": "https://www.gamerpower.com/open/free-nights-into-dreams-steam",
    "published_date": "2020-10-14 19:46:46",
    "type": "Game",
    "platforms": "PC, Steam",
    "end_date": "N/A",
    "users": 200070,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/free-nights-into-dreams-steam",
    "open_giveaway": "https://www.gamerpower.com/open/free-nights-into-dreams-steam"
  },
  {
    "id": 383,
    "title": "Causa, Voices of the Dusk Game Packs Bundle Keys",
    "worth": 14.0,
    "thumbnail": "https://www.gamerpower.com/offers/1/5f68ee0a0c433.jpg",
    "image": "https://www.gamerpower.com/offers/1b/5f68ee0a0c433.jpg",
    "description": "Claim your Causa, Voices of the Dusk Game Packs Bundle Key and unlock 7 Card Packs and 1 Premium Card Back!",
    "instructions": "1. Login into your Alienware account and click the button to unlock your key.\r\n2. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/causa-voices-of-the-dusk-game-packs-bundle-keys",
    "published_date": "2020-09-21 20:16:42",
    "type": "DLC",
    "platforms": "PC",
    "end_date": "N/A",
    "users": 8690,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/causa-voices-of-the-dusk-game-packs-bundle-keys",
    "open_giveaway": "https://www.gamerpower.com/open/causa-voices-of-the-dusk-game-packs-bundle-keys"
  },
  {
    "id": 28,
    "title": "Higurashi When They Cry Hou - Ch.1 Onikakushi",
    "worth": 1.19,
    "thumbnail": "https://www.gamerpower.com/offers/1/5ec62aa074c9b.jpg",
    "image": "https://www.gamerpower.com/offers/1b/5ec62aa074c9b.jpg",
    "description": "Higurashi When They Cry Hou - Ch.1 Onikakushi is currently free on Steam until a vaccine or treatment is discovered!",
    "instructions": "Download on Steam before the offer expires!",
    "open_giveaway_url": "https://www.gamerpower.com/open/higurashi-when-they-cry-hou-ch-1-onikakushi",
    "published_date": "2020-05-15 14:15:44",
    "type": "Game",
    "platforms": "PC, Steam",
    "end_date": "N/A",
    "users": 153350,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/higurashi-when-they-cry-hou-ch-1-onikakushi",
    "open_giveaway": "https://www.gamerpower.com/open/higurashi-when-they-cry-hou-ch-1-onikakushi"
  },
  {
    "id": 154,
    "title": "Battle for the Galaxy Ice Bastion Pack Steam Key",
    "worth": 7.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/1eea55fd841fb.jpg",
    "image": "https://www.gamerpower.com/offers/1b/1eea55fd841fb.jpg",
    "description": "Get your Ice Bastion DLC Pack Steam key for Battle for the Galaxy and unlock premium currency, permanent boosts and more! Please note the base game Battle for the Galaxy (free to play) is required to enjoy this DLC content.",
    "instructions": "1. Login into your Alienware account.\r\n2. Click the button to unlock your Steam Key.\r\n3. Redeem your key on Steam.",
    "open_giveaway_url": "https://www.gamerpower.com/open/battle-for-the-galaxy-ice-bastion-pack-steam-keys",
    "published_date": "2020-03-01 00:00:00",
    "type": "DLC",
    "platforms": "PC, Steam",
    "end_date": "N/A",
    "users": 13190,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/battle-for-the-galaxy-ice-bastion-pack-steam-keys",
    "open_giveaway": "https://www.gamerpower.com/open/battle-for-the-galaxy-ice-bastion-pack-steam-keys"
  },
  {
    "id": 37,
    "title": "Free Endless Space Collection (Steam) Giveaway",
    "worth": 9.99,
    "thumbnail": "https://www.gamerpower.com/offers/1/5ec637bfa0df6.jpg",
    "image": "https://www.gamerpower.com/offers/1b/5ec637bfa0df6.jpg",
    "description": "Grab Endless Space Collection for free on Steam via Games2gether! You just need to follow the instructions below!",
    "instructions": "1. Login or create your free Games2gether account.\r\n2. Go to the reward page and link your Steam account.\r\n3. Go back to the reward page and click the button to redeem your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/free-endless-space-collection",
    "published_date": "2020-01-21 15:11:43",
    "type": "Game",
    "platforms": "PC, Steam",
    "end_date": "N/A",
    "users": 228700,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/free-endless-space-collection",
    "open_giveaway": "https://www.gamerpower.com/open/free-endless-space-collection"
  }
]
